name: PR
on:
  pull_request:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: valitydev/action-frontend/setup-install@v2
      - run: npm run build-editor
